### ISSUE TITLE
Pitch only adjusts in increments of 2, i.e., can set to 24 and 26, but not 25

### ISSUE THREAD

**Issue by raucous1966** [synthmata/ccynthmata#2]
I'm sorry if this is already asked/answered, but is there any way to increase the granularity?

Like, in Reason, I think if you hold down shift, before clicking on a UI element, it gives finer granularity of control.

Regardless, this is an awesome tool, so THANK YOU!

__e

**Comment by synthmata** [comment]
Hi there, this is due to how the Volca receives the midi CC messages for a bunch of the parameters. Midi CCs run from 0-127, but many of the Volca parameters go from 0-255, so essentially if you send a CC value, the Volca doubles it. So this isn't a limitation of the editor, it's just reflecting how the Volca interprets things I'm afraid.
